site_name: Consulta à Legislação de Maricá
docs_dir: docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
palette:
    - scheme: default
      primary: be1622       # vermelho para menu
      accent: 04b2e8        # azul para links
      background: eeedee    # fundo principal
      surface: fcea1d       # cards e elementos secundários
      text: 009d45          # texto principal
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
    - scheme: slate          # dark mode
      primary: be1622
      accent: 74e4fb
      background: 000000    # fundo escuro
      surface: 83bd4c
      text: eeedee
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro

nav:
  - Início: index.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets

plugins:
  - search:
      lang: pt
      separator: '[\s\-\.]+'
  - awesome-pages    